/*
Curve parameters and compile-time configuration for secp256k1.

Every curve constant that varies between the real curve and the reduced-order curves used
by the exhaustive tests lives here, so that swapping curves is a `-define:` away and never
a code edit. This package depends on nothing.

Mirrors the section of upstream's `src/group_impl.h` generated by
`sage/gen_exhaustive_groups.sage`.
*/
package params

/*
Order of the group used for testing. Zero — the default — selects the real secp256k1
curve. A non-zero value selects a reduced-order curve for exhaustive testing, where every
group element can be enumerated.

Only 7, 13 and 199 have known generators; see `GENERATOR_*` below. Set with
`-define:EXHAUSTIVE_ORDER=13`.

Upstream spells this `EXHAUSTIVE_TEST_ORDER`.
*/
EXHAUSTIVE_ORDER :: #config(EXHAUSTIVE_ORDER, 0)

#assert(
	EXHAUSTIVE_ORDER == 0 ||
	EXHAUSTIVE_ORDER == 7 ||
	EXHAUSTIVE_ORDER == 13 ||
	EXHAUSTIVE_ORDER == 199,
	"No known generator for the specified EXHAUSTIVE_ORDER; use 0 (real curve), 7, 13, or 199",
)

/*
Iteration count for randomized tests, mirroring upstream's `COUNT`. Raise it in CI.
*/
COUNT :: #config(COUNT, 64)

#assert(COUNT > 0, "COUNT must be positive")

/*
Whether this build targets the real secp256k1 curve. Prefer this over comparing
EXHAUSTIVE_ORDER at each use site.
*/
IS_REAL_CURVE :: EXHAUSTIVE_ORDER == 0

/*
The `b` coefficient of the curve equation y^2 = x^3 + b. The `a` coefficient is 0 for
every curve here, which is what makes the endomorphism available.

The exhaustive curves are chosen so the field size is identical to secp256k1's — only `b`
and the generator change. Field arithmetic is therefore never affected by
EXHAUSTIVE_ORDER, and the `field` package takes no configuration at all.
*/
when EXHAUSTIVE_ORDER == 0 {
	CURVE_B :: 7
} else when EXHAUSTIVE_ORDER == 7 {
	CURVE_B :: 6
} else when EXHAUSTIVE_ORDER == 13 {
	CURVE_B :: 2
} else {
	CURVE_B :: 4 // EXHAUSTIVE_ORDER == 199
}

/*
The field modulus p = 2^256 - 2^32 - 977, as eight big-endian 32-bit words.

This is the same for every curve configuration above.
*/
FIELD_P :: [8]u32{
	0xffff_fffe, 0xffff_ffff, 0xffff_ffff, 0xffff_ffff,
	0xffff_ffff, 0xffff_ffff, 0xffff_fffe, 0xffff_fc2f,
}

/*
Order of the generator, as eight big-endian 32-bit words.

For the real curve this is n, the secp256k1 group order. For an exhaustive curve it is the
small subgroup order (EXHAUSTIVE_ORDER) in the same eight-word form.
*/
when EXHAUSTIVE_ORDER == 0 {
	GROUP_ORDER :: [8]u32{
		0xffff_ffff, 0xffff_ffff, 0xffff_ffff, 0xffff_fffe,
		0xbaae_dce6, 0xaf48_a03b, 0xbfd2_5e8c, 0xd036_4141,
	}
} else {
	GROUP_ORDER :: [8]u32{0, 0, 0, 0, 0, 0, 0, u32(EXHAUSTIVE_ORDER)}
}

/*
Generator point, as sixteen big-endian 32-bit words: the eight words of x followed by the
eight words of y.

The exhaustive generators are chosen such that the curve equation has the form y^2=x^3+B
for small B, the subgroup has size below 1000, and the subgroup admits the endomorphism
lambda*(x,y) == (beta*x,y). Values are reproduced from upstream's
`sage/gen_exhaustive_groups.sage` output.
*/
when EXHAUSTIVE_ORDER == 0 {
	GENERATOR :: GENERATOR_REAL
} else when EXHAUSTIVE_ORDER == 7 {
	GENERATOR :: GENERATOR_ORDER_7
} else when EXHAUSTIVE_ORDER == 13 {
	GENERATOR :: GENERATOR_ORDER_13
} else {
	GENERATOR :: GENERATOR_ORDER_199
}

/*
Generator for secp256k1, value 'g' defined in "Standards for Efficient Cryptography"
(SEC2) 2.7.1.
*/
GENERATOR_REAL :: [16]u32{
	0x79be_667e, 0xf9dc_bbac, 0x55a0_6295, 0xce87_0b07,
	0x029b_fcdb, 0x2dce_28d9, 0x59f2_815b, 0x16f8_1798,
	0x483a_da77, 0x26a3_c465, 0x5da4_fbfc, 0x0e11_08a8,
	0xfd17_b448, 0xa685_5419, 0x9c47_d08f, 0xfb10_d4b8,
}

GENERATOR_ORDER_7 :: [16]u32{
	0x6662_5d13, 0x317f_fe44, 0x63d3_2cff, 0x1ca0_2b9b,
	0xe5c6_d070, 0x50b4_b05e, 0x81cc_30db, 0xf516_6f0a,
	0x1e60_e897, 0xa7c0_0c7c, 0x2df5_3eb6, 0x9827_4ff4,
	0x6425_2f42, 0x8ca4_4e17, 0x3b25_418c, 0xff4a_b0cf,
}

GENERATOR_ORDER_13 :: [16]u32{
	0xa248_2ff8, 0x4bf3_4edf, 0xa512_62fd, 0xe579_21db,
	0xe0dd_2cb7, 0xa591_4790, 0xbc71_631f, 0xc097_04fb,
	0x9425_36cb, 0xa3e4_9492, 0x3a70_1cc3, 0xee3e_443f,
	0xdf18_2aa9, 0x15b8_aa6a, 0x166d_3b19, 0xba84_b045,
}

GENERATOR_ORDER_199 :: [16]u32{
	0x7fb0_7b5c, 0xd07c_3bda, 0x5539_02e2, 0x7a87_ea2c,
	0x3510_8a7f, 0x051f_41e5, 0xb76a_bad5, 0x1f27_03ad,
	0x0a25_1539, 0x5b4c_4438, 0x952a_634f, 0xac10_dd4d,
	0x6d6f_4745, 0x9899_0c27, 0x3a4f_3116, 0xd32f_f969,
}

/*
Whether the configured exhaustive curve has even order, which changes which group elements
the exhaustive tests may use. Mirrors upstream's
`EXHAUSTIVE_TEST_CURVE_HAS_EVEN_ORDER`.
*/
CURVE_HAS_EVEN_ORDER :: CURVE_B == 1 || CURVE_B == 6 || CURVE_B == 8

/*
The endomorphism constant lambda within the configured exhaustive subgroup, as a small
integer.

On the real curve lambda is a full 256-bit scalar and lives in the `scalar` package; these
values apply only to the reduced-order curves, where the subgroup is small enough that
lambda is a plain integer. Mirrors upstream's `EXHAUSTIVE_TEST_LAMBDA`.

Meaningless when EXHAUSTIVE_ORDER is 0.
*/
when EXHAUSTIVE_ORDER == 7 {
	EXHAUSTIVE_LAMBDA :: 2
} else when EXHAUSTIVE_ORDER == 13 {
	EXHAUSTIVE_LAMBDA :: 9
} else when EXHAUSTIVE_ORDER == 199 {
	EXHAUSTIVE_LAMBDA :: 92
} else {
	EXHAUSTIVE_LAMBDA :: 0
}
