/*
Precomputed tables of generator multiples, and the programs that build them.

Two tables serve the variable-time engine: odd multiples of G, and odd multiples of
2^128*G. The endomorphism-free split of a scalar into two 128-bit halves is what makes the
second one useful.

Upstream generates equivalent tables into a checked-in C source file. Here they are built
at package initialization by the same algorithm, which means:

  - nothing is vendored, so there is no checked-in blob to drift out of sync with the code
    and nothing large for a submodule consumer to clone;
  - the "regenerate and compare" requirement is met continuously rather than by a separate
    step, and `tests/ecmult` additionally verifies each entry against an independently
    computed multiple of G.

The cost is a few milliseconds of startup, kept low by converting all points with a single
batched inversion instead of one inversion per entry.

Mirrors upstream's `ecmult_compute_table_impl.h` and `ecmult_gen_compute_table_impl.h`.
*/
package ecmult

import "../group"
import "../params"
import "../scalar"

/*
Whether the generator tables are embedded in the binary rather than built at start-up.

**On by default.** Building them costs about 12 ms of process start-up, which a long-running
service never notices and a short-lived one is dominated by: a CLI that signs once and
verifies once spent more time building tables than doing cryptography. Embedding takes that
to ~1 ms, at a cost of 1 MB of binary.

Turn it off with `-define:SECP256K1_EMBED_TABLES=false` to build them at start-up instead —
useful on a big-endian target, or to avoid the 1 MB, or to check the two paths agree.

`ecmult/pre_g.bin` is generated by `odin run precompute_ecmult/` and is committed, because
`#load` resolves at compile time and a fresh clone must be able to build. That is a
checked-in artifact, which this file previously argued against on the grounds that it could
drift from the code. The answer to drift is not to avoid the artifact but to check it:
`tests/ecmult` recomputes all 16,384 entries from the curve definition and compares them,
in both modes. For scale, upstream commits 2.55 MB of generated C for the same purpose.
*/
// Requested by the caller, but only honoured for the configuration the blob was generated
// for. It holds real-curve points at the default window size: an exhaustive-order build uses
// a different generator entirely, and a different `ECMULT_WINDOW_SIZE` needs a different
// number of entries. Both fall back to building at start-up. Without this guard the
// exhaustive suite silently multiplies against the wrong curve.
@(private)
EMBED_REQUESTED :: #config(SECP256K1_EMBED_TABLES, true)

EMBED_TABLES :: EMBED_REQUESTED && params.EXHAUSTIVE_ORDER == 0 && ECMULT_WINDOW_SIZE == 15

when EMBED_TABLES {
	// The blob is the tables' in-memory representation, so it is host-endian and reused in
	// place rather than parsed. Every supported target is little-endian; the runtime build
	// below remains available everywhere else.
	#assert(
		ODIN_ENDIAN == .Little,
		"SECP256K1_EMBED_TABLES requires a little-endian target; build the tables at runtime instead",
	)

	// `len()` of a `#load` constant is not constant-evaluable in this Odin version, so the
	// blob's size cannot be checked with `#assert`. `tests/ecmult` checks it at runtime
	// instead, alongside recomputing every entry — a stronger check than the size anyway,
	// since a blob of the right length can still hold the wrong points.
	@(private, rodata)
	TABLE_BLOB := #load("pre_g.bin")

	/*
	Odd multiples of G: [1*G, 3*G, ..., (2*TABLE_SIZE_G - 1)*G].

	Slices over the embedded bytes rather than copies — reinterpreting costs nothing, where
	copying would put a megabyte of memmove back into start-up.

	They are bound in `ensure_var_tables` rather than by an initializer here. A package-level
	initializer runs from Odin's runtime start-up, which a C program linking this as a static
	library never performs — the slices would stay empty and every table lookup would index
	out of range. `csuite` caught exactly that.
	*/
	PRE_G: []group.Ge_Storage

	/*
	Odd multiples of 2^128*G, for the high half of a 256-bit scalar.
	*/
	PRE_G_128: []group.Ge_Storage
} else {
	/*
	Odd multiples of G: [1*G, 3*G, ..., (2*TABLE_SIZE_G - 1)*G].
	*/
	PRE_G: [TABLE_SIZE_G]group.Ge_Storage

	/*
	Odd multiples of 2^128*G, for the high half of a 256-bit scalar.
	*/
	PRE_G_128: [TABLE_SIZE_G]group.Ge_Storage
}

/*
Fills `table` with odd multiples of `gen`: [1*gen, 3*gen, 5*gen, ...].

Each entry is obtained by adding 2*gen to the previous one. Conversions to affine are
batched, so the whole table costs one field inversion rather than one per entry.
*/
compute_table :: proc "contextless" (table: []group.Ge_Storage, gen: ^group.Gej) {
	n := len(table)
	if n == 0 {
		return
	}

	// Build the multiples in Jacobian coordinates first.
	points := make_gej_buffer(n)
	defer_free_gej_buffer(points)

	gj := gen^
	points[0] = gj

	dgen_j: group.Gej
	group.gej_double_var(&dgen_j, gen, nil)
	dgen: group.Ge
	dcopy := dgen_j
	group.ge_set_gej_var(&dgen, &dcopy)

	for j in 1 ..< n {
		acc := points[j - 1]
		group.gej_add_ge_var(&acc, &acc, &dgen, nil)
		points[j] = acc
	}

	// One batched inversion for the whole table.
	affine := make_ge_buffer(n)
	defer_free_ge_buffer(affine)
	group.ge_set_all_gej_var(affine[:n], points[:n])

	for j in 0 ..< n {
		CHECK(!group.ge_is_infinity(&affine[j]), "compute_table: table entry is infinity")
		group.ge_to_storage(&table[j], &affine[j])
	}
}

/*
Fills both generator tables: odd multiples of gen, and of 2^128*gen.
*/
compute_two_tables :: proc "contextless" (
	table: []group.Ge_Storage,
	table_128: []group.Ge_Storage,
	gen: ^group.Ge,
) {
	gj: group.Gej
	group.gej_set_ge(&gj, gen)
	compute_table(table, &gj)

	for _ in 0 ..< 128 {
		group.gej_double_var(&gj, &gj, nil)
	}
	compute_table(table_128, &gj)
}

/*
Storage for table construction.

The tables are built once at initialization, so fixed global scratch avoids both a heap
allocation and a large stack frame. `CLAUDE.md` requires the hot paths to be
allocation-free; this is initialization, but using static storage keeps the rule uniform.
*/
@(private)
table_scratch_gej: [TABLE_SIZE_G]group.Gej
@(private)
table_scratch_ge: [TABLE_SIZE_G]group.Ge

@(private)
make_gej_buffer :: #force_inline proc "contextless" (n: int) -> []group.Gej {
	CHECK(n <= TABLE_SIZE_G, "table scratch too small")
	return table_scratch_gej[:n]
}

@(private)
make_ge_buffer :: #force_inline proc "contextless" (n: int) -> []group.Ge {
	CHECK(n <= TABLE_SIZE_G, "table scratch too small")
	return table_scratch_ge[:n]
}

@(private)
defer_free_gej_buffer :: #force_inline proc "contextless" (_: []group.Gej) {}

@(private)
defer_free_ge_buffer :: #force_inline proc "contextless" (_: []group.Ge) {}

@(private)
var_tables_ready: bool

@(private)
gen_table_ready: bool

/*
Builds the variable-time generator tables if they have not been built yet.

`PRE_G` and `PRE_G_128` together are 1 MB and take roughly 12 ms to construct. Only
`ecmult`, the variable-time engine behind verification, reads them — so this is deliberately
*not* an `@(init)`, and a process that only signs never pays for them.

See `group.ensure_init` for why an explicit initializer exists at all: `@(init)` does not run
when the library is linked into a C program, so every entry point must be able to trigger
its own initialization. Idempotent.
*/
ensure_var_tables :: proc "contextless" () {
	when EMBED_TABLES {
		if var_tables_ready {
			return
		}
		// Nothing to compute — only to point at. Cheap enough to be idempotent without a
		// flag, but the flag keeps the shape identical to the runtime path.
		base := cast([^]group.Ge_Storage)raw_data(TABLE_BLOB)
		PRE_G = base[:TABLE_SIZE_G]
		PRE_G_128 = base[TABLE_SIZE_G:2 * TABLE_SIZE_G]
		var_tables_ready = true
	} else {
		if var_tables_ready {
			return
		}
		group.ensure_init()
		g := group.GENERATOR
		compute_two_tables(PRE_G[:], PRE_G_128[:], &g)
		var_tables_ready = true
	}
}

/*
Builds the signing comb table if it has not been built yet.

Kept separate from `ensure_var_tables` because the two serve opposite paths: this one feeds
`ecmult_gen` and every signing operation, while `PRE_G` feeds verification. Building both
together meant a signing-only process spent ~12 ms on a megabyte of tables it would never
read. Idempotent.
*/
ensure_gen_table :: proc "contextless" () {
	if gen_table_ready {
		return
	}
	group.ensure_init()
	g := group.GENERATOR
	gen_compute_table(&PREC_TABLE, &g)
	gen_table_ready = true
}

/*
Builds every table. This is what `@(init)` runs, and what a C consumer calls through `capi`.

**Do not make this lazy without adding synchronization.** Building on first use looks like an
easy win — the tables are 1 MB and cost ~12 ms, and a signing-only process never reads
`PRE_G` at all — but two threads reaching an unbuilt table concurrently will race, one of
them reading entries the other is still writing. Building eagerly, before any caller exists,
is what makes the unsynchronized `*_ready` flags safe. Measured cost of the eager build is
~12 ms of process start-up; see `TODO.md` for the options for reclaiming it.
*/
ensure_init :: proc "contextless" () {
	ensure_var_tables()
	ensure_gen_table()
}

@(init, private)
init_tables :: proc "contextless" () {
	ensure_init()
}

/*
Returns the scalar 1/2 mod n, used when building the comb table for `ecmult_gen`.

The comb operates on G/2 rather than G, which avoids a modular division by two in the
per-call path.
*/
@(private)
scalar_half_one :: proc "contextless" () -> scalar.Scalar {
	h: scalar.Scalar
	scalar.scalar_half(&h, &scalar.ONE)
	return h
}
