#!/usr/bin/env python3
"""Transcribes the Wycheproof JSON corpora into Odin tables, verbatim.

Every field is copied as-is from the upstream JSON. Nothing is filtered, reordered or
edited: the tcId ordering below is the file's own, so a diff against a regenerated table is
a diff against upstream.
"""
import json, sys, textwrap

SRC = "/home/jdavis/Development/secp256k1-upstream/src/wycheproof"


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def gen_ecdsa(out):
    d = json.load(open(f"{SRC}/ecdsa_secp256k1_sha256_bitcoin_test.json"))
    rows = []
    for g in d["testGroups"]:
        pk = g["publicKey"]["uncompressed"]
        for t in g["tests"]:
            rows.append((t["tcId"], pk, t["msg"], t["sig"],
                         t["result"] == "valid", t["comment"]))
    n_valid = sum(1 for r in rows if r[4])
    with open(out, "w") as f:
        f.write(f'''/*
The Wycheproof ECDSA-secp256k1-SHA256 "bitcoin" corpus, transcribed verbatim.

Source: `src/wycheproof/ecdsa_secp256k1_sha256_bitcoin_test.json` in bitcoin-core/secp256k1
v0.7.1, schema `ecdsa_bitcoin_verify_schema.json`. Generated, not hand-written; regenerating
from the JSON must reproduce this file byte for byte.

{len(rows)} cases, {n_valid} expected-valid and {len(rows) - n_valid} expected-invalid. The
invalid ones carry the weight: they are chosen adversarial inputs — DER encoding abuse,
integer overflow, malleated s, edge-case public keys — that random fuzzing does not reach.

The "bitcoin" variant of this corpus requires strict DER *and* low-S, so a malleable
signature is expected to be rejected even though it is arithmetically valid.

Do not edit this file. `CLAUDE.md`: vectors come from upstream, unmodified.
*/
package test_ecdsa

Wycheproof_Case :: struct {{
	tc_id:   int,
	pubkey:  string, // uncompressed SEC1, 04 || x || y
	msg:     string, // raw message; the digest is SHA-256 of these bytes
	sig:     string, // DER
	valid:   bool,
	comment: string,
}}

WYCHEPROOF_ECDSA := [{len(rows)}]Wycheproof_Case{{
''')
        for tc, pk, msg, sig, valid, comment in rows:
            f.write(f'\t{{{tc}, "{pk}", "{msg}", "{sig}", {str(valid).lower()}, "{esc(comment)}"}},\n')
        f.write("}\n")
    return len(rows), n_valid


def gen_ecdh(out):
    d = json.load(open(f"{SRC}/ecdh_secp256k1_test.json"))
    rows = []
    for g in d["testGroups"]:
        for t in g["tests"]:
            rows.append((t["tcId"], t["public"], t["private"], t.get("shared", ""),
                         t["result"], t["comment"]))
    counts = {}
    for r in rows:
        counts[r[4]] = counts.get(r[4], 0) + 1
    with open(out, "w") as f:
        f.write(f'''/*
The Wycheproof ECDH-secp256k1 corpus, transcribed verbatim.

Source: `src/wycheproof/ecdh_secp256k1_test.json` in bitcoin-core/secp256k1 v0.7.1.
Generated, not hand-written; regenerating from the JSON must reproduce this file byte for
byte.

{len(rows)} cases: {counts}.

`public` is an X.509/DER-wrapped SubjectPublicKeyInfo in this corpus rather than a bare
point, so a case is only run when the trailing uncompressed point can be located; the count
of skipped cases is asserted so a parsing regression cannot silently shrink the corpus.

Results are three-valued upstream. "acceptable" marks inputs that a conforming
implementation may either accept or reject — usually non-canonical encodings — so those are
recorded but not asserted either way.

Do not edit this file. `CLAUDE.md`: vectors come from upstream, unmodified.
*/
package test_ecdh_recovery

Wycheproof_Ecdh_Case :: struct {{
	tc_id:   int,
	public:  string, // DER SubjectPublicKeyInfo
	private: string, // big-endian scalar, may be short or over-long
	shared:  string, // expected x coordinate, empty when the case is invalid
	result:  string, // "valid", "invalid" or "acceptable"
	comment: string,
}}

WYCHEPROOF_ECDH := [{len(rows)}]Wycheproof_Ecdh_Case{{
''')
        for tc, pub, priv, shared, res, comment in rows:
            f.write(f'\t{{{tc}, "{pub}", "{priv}", "{shared}", "{res}", "{esc(comment)}"}},\n')
        f.write("}\n")
    return len(rows), counts


if __name__ == "__main__":
    n, v = gen_ecdsa("/home/jdavis/Development/secp256k1/tests/ecdsa/wycheproof_ecdsa_vectors.odin")
    print(f"ecdsa: {n} cases, {v} valid")
    n, c = gen_ecdh("/home/jdavis/Development/secp256k1/tests/ecdh_recovery/wycheproof_ecdh_vectors.odin")
    print(f"ecdh: {n} cases, {c}")
